services:
  # NexusFi 메인 데이터베이스 (PostgreSQL)
  nexusfi-db:
    image: postgres:16-alpine
    container_name: nexusfi-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "1361"
      POSTGRES_DB: nexusfi
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    networks:
      - nexusfi-network

  # 세션 및 토큰 관리를 위한 캐시 서버 (Redis)
  nexusfi-redis:
    image: redis:7-alpine
    container_name: nexusfi-redis
    ports:
      - "6379:6379"
    networks:
      - nexusfi-network

  # 데이터베이스 관리용 GUI (PgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: nexusfi-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nexusfi.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - nexusfi-db
    networks:
      - nexusfi-network

networks:
  nexusfi-network:
    driver: bridge
