spring:
  application:
    name: nexusfi-server
  
  profiles:
    default: local

  threads:
    virtual:
      enabled: true # Java 21 Virtual Threads 활성화

  config:
    import:
      - database.yml
      - redis.yml
      - cors.yml
      - logging.yml
      - swagger.yml
      - oauth.yml # OAuth2 설정 추가 ✨

server:
  port: 8080
  shutdown: graceful # 안전한 종료 설정
  forward-headers-strategy: framework # 프록시 환경 대응

management:
  endpoints:
    web:
      exposure:
        include: "*"